const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('browser', {
  createTab: (url, partition) => ipcRenderer.invoke('tab:create', { url, partition }),
  activateTab: (id) => ipcRenderer.invoke('tab:activate', id),
  closeTab: (id) => ipcRenderer.invoke('tab:close', id),
  navigate: (id, url) => ipcRenderer.invoke('tab:navigate', { id, url }),
  back: (id) => ipcRenderer.invoke('tab:back', id),
  forward: (id) => ipcRenderer.invoke('tab:forward', id),
  reload: (id) => ipcRenderer.invoke('tab:reload', id),
  getUrl: (id) => ipcRenderer.invoke('tab:getUrl', id),
  getPageText: (id) => ipcRenderer.invoke('tab:getPageText', id),
  canGoBack: (id) => ipcRenderer.invoke('tab:canGoBack', id),
  canGoForward: (id) => ipcRenderer.invoke('tab:canGoForward', id),
  sbOpen: () => ipcRenderer.send('sb:open'),
  trigEnter: () => ipcRenderer.send('trig:enter'),
  trigLeave: () => ipcRenderer.send('trig:leave'),
  sbClose: () => ipcRenderer.send('sb:close'),
  hideUI: () => ipcRenderer.send('ui:hide'),
  showUI: () => ipcRenderer.send('ui:show'),
  setPassthrough: (pass) => ipcRenderer.send('ui:passthrough', pass),
  importDetect: () => ipcRenderer.invoke('import:detect'),
  importBookmarks: (browser) => ipcRenderer.invoke('import:bookmarks', browser),
  importPasswordsCsv: (csv) => ipcRenderer.invoke('import:passwords:csv', csv),
  importPasswordsAuto: (browser) => ipcRenderer.invoke('import:passwords:auto', browser),
  getPasswords: () => ipcRenderer.invoke('import:passwords:get'),
  fillCredentials: (id, user, pass) => ipcRenderer.invoke('tab:fillCredentials', { id, user, pass }),
  importCookies: (browser) => ipcRenderer.invoke('import:cookies', browser),
  openPasswordWindow: () => ipcRenderer.send('passwords:open-window'),
  saveLoginHistory: (entry) => ipcRenderer.invoke('login-history:save', entry),
  getLoginHistory: () => ipcRenderer.invoke('login-history:get'),
  deleteLoginHistory: (id) => ipcRenderer.invoke('login-history:delete', id),
  clearLoginHistory: () => ipcRenderer.invoke('login-history:clear'),
  autoLogin: (tabId, entry) => ipcRenderer.invoke('login-history:auto-login', { tabId, entry }),
  installUpdate: () => ipcRenderer.send('update:install'),
  checkUpdate: () => ipcRenderer.invoke('update:check'),
  // 通知
  getNotifSettings: () => ipcRenderer.invoke('notif:getSettings'),
  saveNotifSettings: (s) => ipcRenderer.invoke('notif:saveSettings', s),
  // イベント
  onReady: (cb) => ipcRenderer.on('app:ready', cb),
  onOpenUrl: (cb) => ipcRenderer.on('app:openUrl', (e, url) => cb(url)),
  onNavigate: (cb) => ipcRenderer.on('tab:navigate', (e, d) => cb(d)),
  onTitle: (cb) => ipcRenderer.on('tab:title', (e, d) => cb(d)),
  onFavicon: (cb) => ipcRenderer.on('tab:favicon', (e, d) => cb(d)),
  onFaviconFallback: (cb) => ipcRenderer.on('tab:favicon:fallback', (e, d) => cb(d)),
  onLoading: (cb) => ipcRenderer.on('tab:loading', (e, d) => cb(d)),
  onActivated: (cb) => ipcRenderer.on('tab:activated', (e, d) => cb(d)),
  onUpdateAvailable: (cb) => ipcRenderer.on('update:available', (e, d) => cb(d)),
  onUpdateDownloaded: (cb) => ipcRenderer.on('update:downloaded', (e, d) => cb(d)),
  onUpdateNotAvailable: (cb) => ipcRenderer.on('update:notAvailable', cb),
  onNotifSettings: (cb) => ipcRenderer.on('notif:settings', (e, d) => cb(d)),
  onNotifClick: (cb) => ipcRenderer.on('notif:click', (e, d) => cb(d)),
  onNotifHub: (cb) => ipcRenderer.on('notif:hub', (e, d) => cb(d)),
  onZoomChanged: (cb) => ipcRenderer.on('zoom:changed', (e, pct) => cb(pct)),
  // 履歴
  getHistory: () => ipcRenderer.invoke('history:get'),
  clearHistory: () => ipcRenderer.invoke('history:clear'),
  // ダウンロード履歴
  getDownloadHistory: () => ipcRenderer.invoke('download:getHistory'),
  clearDownloadHistory: () => ipcRenderer.invoke('download:clearHistory'),
  onDownloadDone: (cb) => ipcRenderer.on('download:done', (e, d) => cb(d)),
  // アプリ状態の永続化（ワークスペース・タブ）
  saveAppState: (state) => ipcRenderer.invoke('state:save', state),
  loadAppState: () => ipcRenderer.invoke('state:load'),
  setLayout: (layout) => ipcRenderer.invoke('layout:set', layout),
  onSaveRequest: (cb) => ipcRenderer.on('app:save-before-quit', cb),
  onTrigEnter: (cb) => ipcRenderer.on('trig:enter', cb),
  onTrigLeave: (cb) => ipcRenderer.on('trig:leave', cb),
  saveComplete: () => ipcRenderer.send('app:save-complete'),
  onExtInstalled: (cb) => ipcRenderer.on('ext:installed', (e, d) => cb(d)),
  installExtension: (extId) => ipcRenderer.invoke('ext:install', extId),
  getExtensions: () => ipcRenderer.invoke('ext:list'),
  openExtensionPopup: (extId) => ipcRenderer.invoke('ext:openPopup', extId),
  uninstallExtension: (extId) => ipcRenderer.invoke('ext:uninstall', extId),
  getExtIcon: (iconPath) => ipcRenderer.invoke('ext:icon', iconPath),
  toggleExtension: (extId) => ipcRenderer.invoke('ext:toggle', extId),
  zoomIn: (id) => ipcRenderer.invoke('tab:zoomIn', id),
  zoomOut: (id) => ipcRenderer.invoke('tab:zoomOut', id),
  zoomReset: (id) => ipcRenderer.invoke('tab:zoomReset', id),
  getZoom: (id) => ipcRenderer.invoke('tab:getZoom', id),
  // セッション情報の保存
  saveSessionInfo: (wsIdx, info) => ipcRenderer.invoke('state:saveSession', { wsIdx, info }),
  // アップデート進捗
  onUpdateProgress: (cb) => ipcRenderer.on('update:progress', (e, d) => cb(d)),
  // テーマ
  setTheme: (dark) => ipcRenderer.send('theme:set', dark),
  openAIWindow:  () => ipcRenderer.send('ai:open-window'),
  closeAIWindow: () => ipcRenderer.send('ai:close-window'),
  onAIWindowClosed: (cb) => ipcRenderer.on('ai:window-closed', cb),
  // 分割
  setSplit: (ids) => ipcRenderer.invoke('split:set', ids),
  clearSplit: () => ipcRenderer.invoke('split:clear'),
  // favicon取得（main process経由でfetchしdataURIを返す）
  fetchFavicon: (url) => ipcRenderer.invoke('favicon:fetch', url),
  clearAllExtensions: () => ipcRenderer.invoke('ext:clear-all'),
  ytdlpCheck: () => ipcRenderer.invoke('ytdlp:check'),
  ytdlpInstall: () => ipcRenderer.invoke('ytdlp:install'),
  ytdlpDownload: (url, quality) => ipcRenderer.invoke('ytdlp:download', { url, quality }),
  getProxy: () => ipcRenderer.invoke('proxy:get'),
  setProxy: (s) => ipcRenderer.invoke('proxy:set', s),
  send: (ch, ...args) => {
    const allowed = ['ui:modal-state'];
    if (allowed.includes(ch)) ipcRenderer.send(ch, ...args);
  },
});
