const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('browser', {
  createTab: (url) => ipcRenderer.invoke('tab:create', url),
  activateTab: (id) => ipcRenderer.invoke('tab:activate', id),
  closeTab: (id) => ipcRenderer.invoke('tab:close', id),
  navigate: (id, url) => ipcRenderer.invoke('tab:navigate', { id, url }),
  back: (id) => ipcRenderer.invoke('tab:back', id),
  forward: (id) => ipcRenderer.invoke('tab:forward', id),
  reload: (id) => ipcRenderer.invoke('tab:reload', id),
  getUrl: (id) => ipcRenderer.invoke('tab:getUrl', id),
  canGoBack: (id) => ipcRenderer.invoke('tab:canGoBack', id),
  canGoForward: (id) => ipcRenderer.invoke('tab:canGoForward', id),
  sbOpen: () => ipcRenderer.send('sb:open'),
  sbClose: () => ipcRenderer.send('sb:close'),
  importDetect: () => ipcRenderer.invoke('import:detect'),
  importBookmarks: (browser) => ipcRenderer.invoke('import:bookmarks', browser),
  installUpdate: () => ipcRenderer.send('update:install'),
  // 通知
  getNotifSettings: () => ipcRenderer.invoke('notif:getSettings'),
  saveNotifSettings: (s) => ipcRenderer.invoke('notif:saveSettings', s),
  sendNotif: (d) => ipcRenderer.send('notif:send', d),
  // イベント
  onReady: (cb) => ipcRenderer.on('app:ready', cb),
  onOpenUrl: (cb) => ipcRenderer.on('app:openUrl', (e, url) => cb(url)),
  onNavigate: (cb) => ipcRenderer.on('tab:navigate', (e, d) => cb(d)),
  onTitle: (cb) => ipcRenderer.on('tab:title', (e, d) => cb(d)),
  onFavicon: (cb) => ipcRenderer.on('tab:favicon', (e, d) => cb(d)),
  onLoading: (cb) => ipcRenderer.on('tab:loading', (e, d) => cb(d)),
  onActivated: (cb) => ipcRenderer.on('tab:activated', (e, d) => cb(d)),
  onUpdateAvailable: (cb) => ipcRenderer.on('update:available', (e, d) => cb(d)),
  onUpdateDownloaded: (cb) => ipcRenderer.on('update:downloaded', (e, d) => cb(d)),
  onNotifSettings: (cb) => ipcRenderer.on('notif:settings', (e, d) => cb(d)),
  onNotifClick: (cb) => ipcRenderer.on('notif:click', (e, d) => cb(d)),
});
